/**
 * File 2 of 3 — the report template (merges the old 11 page-header-footer + 12 page-number + 13
 * system-field-anchor into one "page frame" demo).
 *
 * The page frame is the layer that repeats on every page, wrapping the flowing content:
 *   - page header / footer  → `report.pageHeader.addBlock(...)` / `report.pageFooter.addBlock(...)`
 *       declarative block bands that RESERVE height — content starts below the header and ends
 *       above the footer, on every page (including pages AutoTable makes on its own).
 *   - page number           → `.pageNumber(...)`
 *       drawn INSIDE the existing margin, so unlike the bands it reserves NO content-area height.
 *       Its `format` string uses the system-field tokens {pageNumber} / {totalPages}.
 *
 * The header's "Printed" date is resolved at build time via formatTimestamp (a plain string in the
 * block tree). For a raw band with live {date}/{dateTime} tokens instead, see createAnchoredBand().
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { col, formatTimestamp, reportBuilder } from '../../src/index';
import type { KapomReport, ReportNodeInput, RGB, TableNode } from '../../src/index';
import { fontConfig } from '../shared';
import type { StockRow } from './data';

const here = dirname(fileURLToPath(import.meta.url));
const logo = new Uint8Array(readFileSync(join(here, '../../src/assets/kapom-report.png')));

const NAVY: RGB = [31, 63, 112];
const GRAY: RGB = [110, 110, 110];
const RULE: RGB = [205, 210, 218];

/** the page-header band: logo + company (left) and report title + printed date (right) — repeats every page */
function headerRow(printedAt: string): ReportNodeInput {
  return {
    type: 'row',
    columns: [
      { width: 14, children: [{ type: 'image', data: logo, format: 'PNG', width: 14, height: 14 }] },
      {
        children: [
          { type: 'spacer', height: 2 },
          { content: 'Kapom Report', style: { fontSize: 13, fontStyle: 'bold', color: NAVY } },
          { content: 'kapom-soft', style: { fontSize: 8, color: GRAY } },
        ],
      },
      {
        children: [
          { content: 'Inventory Report', align: 'right', style: { fontSize: 14, fontStyle: 'bold', color: NAVY } },
          { content: `Printed: ${printedAt}`, align: 'right', style: { fontSize: 8, color: GRAY } },
        ],
      },
    ],
  };
}

export function buildInventoryReport(stock: StockRow[]): KapomReport {
  const c = col<StockRow>();
  const stockTable: TableNode<StockRow> = {
    type: 'table',
    columns: [
      c.rowNumber({ align: 'right', width: 12 }),
      c.data('sku', 'SKU', { width: 34 }),
      c.data('item', 'Item'),
      c.data('qty', 'Qty', { align: 'right', aggregate: 'sum' }),
    ],
    data: stock,
    summaryLabel: 'Total',
    style: { header: { fillColor: NAVY }, zebra: { even: [240, 244, 249] } },
  };

  const report = reportBuilder<StockRow>().font(fontConfig);

  // ── the page frame ──
  report.pageHeader
    .addBlock(headerRow(formatTimestamp(new Date())))
    .addBlock({ type: 'spacer', height: 1.5 })
    .addBlock({ type: 'divider', thickness: 0.3, color: NAVY })
    .addBlock({ type: 'spacer', height: 2 });

  report.pageFooter.addBlock(
    { type: 'divider', thickness: 0.2, color: RULE },
    { type: 'spacer', height: 1 },
    { content: 'Generated by kapom-report', style: { fontSize: 8, color: GRAY } },
  );

  // page number — margin-only (reserves no content-area height). Three ways to set it:
  //   .pageNumber(true)              → default: bottom-left, '{pageNumber} / {totalPages}'
  //   .pageNumber('bottom-right')    → just move it, keep the default format
  //   .pageNumber({ position, format }) → full control (used here)
  report.pageNumber({ position: 'bottom-right', format: 'Page {pageNumber} of {totalPages}' });

  // ── content ── the table is the first (and only) content block, so it starts at contentTop
  // (right below the header) and paginates cleanly. A block before a page-spanning table would
  // leave the cursor mid-page, and the engine's measureHeight estimate would break before the
  // table even starts — see CLAUDE.md notes on table pagination.
  report.content(stockTable);

  return report.build();
}
