/**
 * Demo — SystemField + Anchor Position (roadmap 7)
 * Focus: createAnchoredBand() composes an Anchor[] into a single PageBand, instead of
 * hand-writing a render callback like 05-page-header-footer does — format strings use
 * {token} (date/time/dateTime), substituted via the SystemField resolver
 * The page number itself is NOT one of the footer's anchors — see examples/14-page-number.ts,
 * which uses the dedicated `pageNumber` option so it doesn't cost the footer band any extra height
 * Uses createKapomReport({ blocks, pageHeader, pageFooter, pageNumber }) — the facade calls finalize() for you
 */
import { createKapomReport, createAnchoredBand } from '../src/index';
import type { TableNode } from '../src/index';
import { fontConfig, saveReport } from './shared';

interface Row {
  n: number;
  label: string;
}

const rows: Row[] = Array.from({ length: 80 }, (_, i) => ({
  n: i + 1,
  label: `Item ${i + 1} — sample content to push the table long enough to span multiple pages`,
}));

const bigTable: TableNode<Row> = {
  type: 'table',
  columns: [
    { type: 'rowNumber', header: '#', align: 'right', width: 12 },
    { type: 'data', key: 'label', header: 'Item' },
  ],
  data: rows,
};

const report = createKapomReport<Row>({
  font: fontConfig,
  pageHeader: createAnchoredBand({
    height: 16,
    anchors: [
      { align: 'left', format: 'Kapom Report — Demo', style: { fontStyle: 'bold', color: [41, 128, 185] } },
      { align: 'right', format: '{date}', style: { color: [41, 128, 185] } },
    ],
  }),
  // Compared to 05-page-header-footer, which hand-writes a render callback — here it's a plain
  // format string via {dateTime}, no need to touch doc.setFontSize/setTextColor
  pageFooter: createAnchoredBand({
    height: 12,
    anchors: [{ align: 'left', format: 'Generated by kapom-report — {dateTime}', style: { color: [120, 120, 120] } }],
    // dateFormat.locale can be overridden per report — e.g. 'th-TH' renders the Thai Buddhist calendar
    dateFormat: { locale: 'en-US', dateStyle: 'medium', timeStyle: 'short' },
  }),
  // lightweight page number — drawn inside the page margin, doesn't reserve any content-area
  // height (unlike the anchor above, which is part of the reserved pageFooter band)
  pageNumber: { position: 'bottom-right', format: 'Page {pageNumber} of {totalPages}', style: { color: [120, 120, 120] } },
  blocks: [
    bigTable,
    { type: 'spacer', height: 6 },
    {
      type: 'text',
      content: 'header/footer composed from createAnchoredBand() — no need to hand-write a render callback',
      style: { fontSize: 10, fontStyle: 'bold' },
    },
  ],
});

saveReport(report, '09-system-field-anchor');
