/**
 * Demo — Page Header/Footer band (roadmap 6a)
 * Focus: reserved height is subtracted from the content area; the band is redrawn on every
 * page, including pages AutoTable creates on its own (not just pages engine.breakPage makes)
 * The page number itself is NOT drawn here — see examples/12-page-number.ts, which uses the
 * dedicated `pageNumber` option instead of bundling "Page X of Y" into this reserved footer band
 * Uses createKapomReport({ blocks, pageHeader, pageFooter, pageNumber }) — the facade calls finalize() for you
 */
import { createKapomReport } from '../src/index';
import type { TableNode } from '../src/index';
import { fontConfig, outPath } from './shared';

interface Row {
  n: number;
  label: string;
}

const rows: Row[] = Array.from({ length: 80 }, (_, i) => ({
  n: i + 1,
  label: `Item ${i + 1} — sample content to push the table long enough to span multiple pages`,
}));

const bigTable: TableNode<Row> = {
  type: 'table',
  columns: [
    { type: 'rowNumber', header: '#', align: 'right', width: 12 },
    { type: 'data', key: 'label', header: 'Item' },
  ],
  data: rows,
};

const report = createKapomReport<Row>({
  font: fontConfig,
  // page header — repeats on every page, reserves 16mm at the top (content starts below this line)
  pageHeader: {
    height: 16,
    render: (c) => {
      c.doc.setFontSize(9);
      c.doc.setFont('Sarabun', 'bold');
      c.doc.setTextColor(41, 128, 185);
      c.drawText('Kapom Report — Demo', c.x, c.y + 8);
      c.doc.setDrawColor(41, 128, 185);
      c.doc.setLineWidth(0.3);
      c.doc.line(c.x, c.y + c.height - 1, c.x + c.width, c.y + c.height - 1);
    },
  },
  // page footer — just the generated-by line; the page number lives in `pageNumber` below instead,
  // so it doesn't cost this reserved band any extra height
  pageFooter: {
    height: 12,
    render: (c) => {
      c.doc.setFontSize(8);
      c.doc.setFont('Sarabun', 'normal');
      c.doc.setTextColor(120, 120, 120);
      c.drawText('Generated by kapom-report', c.x, c.y + 6);
    },
  },
  // lightweight page number — drawn inside the page margin, doesn't reserve any content-area height
  // (compare with the old approach of drawing "Page X of Y" inside pageFooter above)
  pageNumber: 'bottom-right',
  // The table is the first block — the cursor sits exactly at contentTop (below the header), so the
  // table starts on page 1 immediately, instead of ensureSpace pushing it to page 2 (an 80-row table
  // always spans more than one page — if a block came before it, the cursor wouldn't be at the top of
  // the page and the engine would break before starting, which would cut the table off right away).
  blocks: [
    bigTable,
    { type: 'spacer', height: 6 },
    {
      type: 'text',
      content: 'A table spanning many pages — header/footer appear on every page, including ones AutoTable creates on its own',
      style: { fontSize: 10, fontStyle: 'bold' },
    },
  ],
});

report.save(outPath('11-page-header-footer'));
console.log(`OK 11-page-header-footer.pdf (${report.doc.getNumberOfPages()} pages)`);
